server:
  port: 9773
spring:
  datasource:
    initialization-mode: never
    druid:
      url: jdbc:mysql://127.0.0.1:3306/db_account?useSSL=false&serverTimezone=UTC
      username: root
      password: root

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

seata:
  registry:
    nacos:
      serverAddr: localhost

