server:
  port: 9772
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_order?useSSL=false&serverTimezone=UTC
      username: root
      password: root
  sql:
    init:
      mode: always