server:
  port: 9772
spring:
  datasource:
    initialization-mode: never
    druid:
      url: jdbc:mysql://localhost:3306/db_order?useSSL=false&serverTimezone=UTC
      username: root
      password: root

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

seata:
  registry:
    nacos:
      serverAddr: localhost