spring:
  application:
    name: business-service

server:
  port: 9770

seata:
  enabled: true
  tx-service-group: loadTestGroup
  use-jdk-proxy: false
  service:
    disable-global-transaction: false
    enable-degrade: false
    vgroup-mapping:
      loadTestGroup: loadTestCluster
    grouplist:
      loadTestCluster: seata-server:8091
  log:
    exception-rate: 100
  client:
    rm:
      async-commit-buffer-limit: 1000
      lock:
        retry-interval: 100
        retry-policy-branch-rollback-on-conflict: true
        retry-times: 300
      report-retry-count: 5
      report-success-enable: false
      table-meta-check-enable: false
      saga-branch-register-enable: false
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true
  config:
    type: file
  registry:
    type: file

