apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: default
  labels:
    k8s-app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: order
  template:
    metadata:
      labels:
        k8s-app: order
    spec:
      containers:
        - name: order
          image: registry-vpc.cn-shenzhen.aliyuncs.com/org-ypq/order:0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9772
              protocol: TCP
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          env:
            ######### 配置 环境变量 命名格式为 aliyun_logs_${logstore名字}_${参数}###########
            ######### 配置 project，如果使用k8s集群默认的project可以不填 ###########
            - name: aliyun_logs_order-stdout_project
              value: k8s-log-sls
            ######### 配置 机器组，如果使用k8s集群默认的project下的默认机器组可以不填 ###########
            # - name: aliyun_logs_provider-stdout_machinegroup
            #   value: k8s-group-app-alpine
            ######### 设置标准输出和错误输出的logstore provider-stdout###########
            - name: aliyun_logs_order-stdout
              value: stdout
            ######### 日志保留时间，只对单个logstore生效 ###########
            - name: aliyun_logs_order-stdout_ttl
              value: "1"
            ######### 日志分区数，只对单个logstore生效 ###########
            - name: aliyun_logs_order-stdout_shard
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
  labels:
    k8s-app: order-service
spec:
  type: ClusterIP
  #  可选NodePort,下面也能指定nodePort=30000~32676
  #  type: NodePort
  ports:
    - port: 9772
      targetPort: 9772
      #      nodePort: 30000
      name: order
  selector:
    k8s-app: order