apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-server
  namespace: default
  labels:
    k8s-app: seata-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: seata-server
  template:
    metadata:
      labels:
        k8s-app: seata-server
    spec:
      containers:
        - name: seata-server
          image: registry-vpc.cn-shenzhen.aliyuncs.com/org-ypq/seata-offical:1.4.2
          imagePullPolicy: Always
          env:
            - name: SEATA_PORT
              value: db
            - name: SEATA_CONFIG_NAME
              value: file:/root/seata-config/registry
            ######### 配置 环境变量 命名格式为 aliyun_logs_${logstore名字}_${参数}###########
            ######### 配置 project，如果使用k8s集群默认的project可以不填 ###########
            - name: aliyun_logs_seata-filelog_project
              value: k8s-log-sls
            ######### 配置 机器组，如果使用k8s集群默认的project下的默认机器组可以不填 ###########
            # - name: aliyun_logs_provider-stdout_machinegroup
            #   value: k8s-group-app-alpine
            ######### 设置标准输出和错误输出的logstore provider-stdout###########
            - name: aliyun_logs_seata-filelog
              value: /root/logs/seata/seata-server.*.all.log
            ######### 日志保留时间，只对单个logstore生效 ###########
            - name: aliyun_logs_seata-filelog_ttl
              value: "1"
            ######### 日志分区数，只对单个logstore生效 ###########
            - name: aliyun_logs_seata-filelog_shard
              value: "1"
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - name: seata-config
              mountPath: /root/seata-config
      volumes:
        - name: seata-config
          configMap:
            name: seata-server-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
data:
  registry.conf: |
    registry {
      type = "file"
    }
    config {
      type = "file"
      file {
          name = "file:/root/seata-config/file.conf"
      }
    }

  file.conf: |
    store {
      mode = "db"
      db {
        datasource = "druid"
        dbType = "mysql"
        driverClassName = "com.mysql.cj.jdbc.Driver"
        url = "jdbc:mysql://rm-wz9k19uh61g95rbzz.mysql.rds.aliyuncs.com:3306/seata"
        user = "ypq"
        password = "1qaz@WSX"
        minConn = 5
        maxConn = 30
        globalTable = "global_table"
        branchTable = "branch_table"
        lockTable = "lock_table"
        queryLimit = 100
        maxWait = 5000
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  namespace: default
  labels:
    k8s-app: seata-server
spec:
  type: ClusterIP
  #  可选NodePort,下面也能指定nodePort=30000~32676
  #  type: NodePort
  ports:
    - port: 8091
      targetPort: 8091
      #      nodePort: 30000
      name: seata-server
  selector:
    k8s-app: seata-server