server:
  port: 9771
spring:
  datasource:
    initialization-mode: never
    url: jdbc:mysql://localhost:3306/db_storage?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

seata:
  registry:
    nacos:
      serverAddr: localhost
logging:
  level:
    org:
      ypq: debug
debug: true