nacos:
  ip: localhost

server:
  port: 9771
spring:
  datasource:
    initialization-mode: never
    url: jdbc:mysql://localhost:3306/db_storage?useSSL=false&serverTimezone=UTC
    username: root
    password: root
