# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build & push image, kustomize to aliyun ack

on:
  push:
    branches: [ at-k8s ]
  pull_request:
    branches: [ at-k8s ]

env:
  REGION_ID: cn-shenzhen
  REGISTRY: registry.cn-shenzhen.aliyuncs.com
  REGISTRY_VPC: registry-vpc.cn-shenzhen.aliyuncs.com
  NAMESPACE: org-ypq
  TAG: 0.1-SNAPSHOT
  ACK_CLUSTER_ID: ced2c8444b1c545238ec67c063287c73d
  ACK_DEPLOYMENT_NAME: account
  KUSTOMIZATION_PATH: k8s/base

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1.1 checkout
      - name: checkout source code
      - uses: actions/checkout@v2
